Fixes #59 — option to not load bashmatic at login
 * added -l flag to bashmatic-install to not invoke
   bashmatic-load-at-login function.

 * Additionally, enhance the bin/bashmatic helper
   to a) try to execute bashmatic.$1 if defined, and
   b) report and error if no function under either name
   is found.

diff --git a/bin/bashmatic b/bin/bashmatic
--- a/bin/bashmatic
+++ b/bin/bashmatic
@@ -20,7 +20,15 @@
 [[ -z ${BASHMATIC_HOME} ]] && export BASHMATIC_HOME="$(dirname $(cd $(dirname "${BASH_SOURCE[0]:-${(%):-%x}}") || exit 1; pwd -P))"
 source "${BASHMATIC_HOME}/init.sh"
 
-if is.a-function "$1"; then
-  eval "$@"
+__func="$1"
+shift
+
+if is.a-function "${__func}"; then
+  eval "${__func} $@"
+elif is.a-function "bashmatic.${__func}"; then
+  eval "bashmatic.${__func} $@"
+else
+  error "Can't find a valid function based on the argument ${bldylw}${__func}"
+  exit 1
 fi
 
