Fixing tests, init.sh and a bunch of other tweaks; v1.0.0

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,38 +1,70 @@
 #!/usr/bin/env bash
+# vim: ft=sh
+set -e
 
-purrent="$(pwd)"
+export clr='\e[0m'       # Text Reset
+export bldblk='\e[1;30m' # Black - Bold
+export bldred='\e[1;31m' # Red
+export bldgrn='\e[1;32m' # Green
+export bldylw='\e[1;33m' # Yellow
+export bldblu='\e[1;34m' # Blue
+export bldpur='\e[1;35m' # Purple
+export bldcyn='\e[1;36m' # Cyan
+export bldwht='\e[1;37m' # White
 
-set -e -x
+puts() {
+  printf "${bldgrn}✓   ${bldblu}${*}${clr}\n"
+}
+
+err() {
+  printf "${bldred}ERROR:\n"
+  for s in "${@}"; do
+    printf "${bldred}✘   ${bldylw}${s}${clr}\n"
+  done
+}
 
 which -s git || {
-  echo "Please install xcode command line tools, "
-  echo "by running: xcode-select --install"
+  puts "Please install xcode command line tools, "
+  puts "by running: xcode-select --install"
   exit 1
 }
 
-cd "${HOME}"
+bashmatic.git.sync() {
+  cd "${BASHMATIC_HOME}" >/dev/null
 
-if [[ -d .bashmatic ]]; then
-  echo "It appears BashMatic is already installed locally..."
-  cd .bashmatic
   if [[ -n $(git status -s) ]]; then
-    echo "Looks like your .bashmattic folder has some locally modified files."
-    echo "Please commit, stash or remove those files, and re-run this setup."
+    err "Looks like your .bashmatic folder exists, and has some locally modified files." \
+      "Please commit, stash or remove those files, and re-run this setup." \
+      "Folder: ${bldpur}${BASHMATIC_HOME}, ${bldylw}git status:"
+    echo
+    git status -s -u
+    echo
     exit 1
   fi
-  git checkout master
-  git pull --rebase
+
+  (git checkout master && git pull --rebase) >/dev/null
+
+  cd - >/dev/null
+}
+
+export BASHMATIC_HOME="${HOME}/.bashmatic"
+export BASHMATIC_INIT="${HOME}/.bashmatic/init.sh"
+export BASHMATIC_URL="https://github.com/kigster/bashmatic"
+
+if [[ -d ${BASHMATIC_HOME} && -f ${BASHMATIC_HOME}/init.sh ]]; then
+  bashmatic.git.sync
 else
-  git clone https://github.com/kigster/bashmatic .bashmatic
+  git clone ${BASHMATIC_URL} ${BASHMATIC_HOME} >/dev/null
 fi
 
-cd "${HOME}"
-
-source ${HOME}/.bashmatic/init.sh
-bashmatic.load-at-login
-
-success "Your BashMatic has been successfully installed."
-
-if [[ ${purrent} != ${HOME} ]]; then
-  cd ${purrent} >/dev/null
-end
+if [[ -s "${BASHMATIC_INIT}" ]]; then
+  # shellcheck disable=SC1090
+  source "${BASHMATIC_INIT}"
+  bashmatic.load-at-login
+  success "Your BashMatic has been successfully installed."
+  exit 0
+else
+  err "Bashmatic did not install correctly, please run the following command by hand:"
+  err "${bldgrn}git clone ${BASHMATIC_URL} ${BASHMATIC_HOME}"
+  exit 1
+fi
