Refactor/improve bootstrapping on OSX

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,22 +1,26 @@
-#!/usr/bin/env bash
+  #!/usr/bin/env bash
 # vim: ft=bash
-# 
-# The purpose of this script is to bootstrap Bashmatic on a 
-# new system. We are supporting OS-X and Linux, although on 
+#
+# The purpose of this script is to bootstrap Bashmatic on a
+# new system. We are supporting OS-X and Linux, although on
 # OS-X we do a lot more initialization to ensure Bashmatic
 # can properly function.
 #
 # Bootstrap script is required to run at least once on a new
 # system, which happens automatically if you install it via
-# 
+#
 # bash -c "$(curl -fsSL https://bashmatic.re1.re)"
 #
 set -e
 
-# Configuration 
+# Configuration
 export HOME=${HOME:-"/"}
 export BASHMATIC_HOME="${HOME}/.bashmatic"
 export BASHMATIC_INIT="${HOME}/.bashmatic/init.sh"
+declare -a CHOWN_DIRS
+declare -a BREW_PACKAGES
+export CHOWN_DIRS=(/usr/local /Library/Ruby /Library/Python)
+export BREW_PACKAGES=(coreutils gnu-sed)
 
 if [[ ${USER} == "kig" ]]; then
   export BASHMATIC_URL="git@github.com:kigster/bashmatic"
@@ -26,6 +30,7 @@ fi
 
 # Constants
 export clr='\e[0m'       # Text Reset
+
 export bldblk='\e[1;30m' # Black - Bold
 export bldred='\e[1;31m' # Red
 export bldgrn='\e[1;32m' # Green
@@ -35,6 +40,16 @@ export bldpur='\e[1;35m' # Purple
 export bldcyn='\e[1;36m' # Cyan
 export bldwht='\e[1;37m' # White
 
+export txtblk='\e[0;30m' # Black - Regular
+export txtred='\e[0;31m' # Red
+export txtgrn='\e[0;32m' # Green
+export txtylw='\e[0;33m' # Yellow
+export txtblu='\e[0;34m' # Blue
+export txtpur='\e[0;35m' # Purple
+export txtcyn='\e[0;36m' # Cyan
+export txtwht='\e[0;37m' # White
+
+
 # Output Helpers
 
 ts() {
@@ -42,28 +57,34 @@ ts() {
 }
 
 puts() {
-  printf "${bldblu}INFO  ${bldwht}|$(ts)| ${clr}${*}${clr}\n"
+  printf "${bldblu} INFO  ${txtpur}〈$(ts)〉 ${txtcyn}${*}${clr}\n"
 }
 
 err() {
   printf "${bldred}_______  ${clr}\n"
   printf "${bldred}       ⤵${clr}\n"
   for str in "$@"; do
-  printf "${bldred}ERROR ${bldwht}|$(ts)| ${bldred}$str\n"
+    printf "${bldred} ERROR ${txtpur}〈$(ts)〉 ${bldred}${str}\n"
   done
 }
 
+
+#——————————————————————————————————————————————————————————————————————————————————————
 # Sudo Helpers
+#——————————————————————————————————————————————————————————————————————————————————————
 sudo-ask() {
-  echo "Please enter your SUDO password if asked..."
-  sudo echo
+  sudo -n true 2>/dev/null || {
+    puts "Please enter your SUDO password: "
+    sudo -v 
+  } 
 }
 
 sudo-enable() {
   sudo mkdir -p "${bootstrap__sudoers_dir}"
   [[ -s ${bootstrap__sudoers_dir}/${USER} ]] || {
-    echo "${USER}" 'ALL=(ALL) NOPASSWD: ALL' | \
-      sudo tee -a "${bootstrap__sudoers_dir}/${USER}"
+    echo "${USER}" 'ALL=(ALL) NOPASSWD: ALL' |
+      sudo tee -a "${bootstrap__sudoers_dir}/${USER}" >/dev/null
+    trap "sudo-disable" EXIT
   }
 }
 
@@ -71,62 +92,90 @@ sudo-disable() {
   sudo rm -f "${bootstrap__sudoers_dir}/${USER}"
 }
 
-# Bash Installer Helpers
-bash-install() {
-  local version="${bootstrap__bash_version}"
-  echo "Installing BASH version ${version}, please wait..."
-  bash-compile "${version}" >/dev/null
+#——————————————————————————————————————————————————————————————————————————————————————
+# BASH Upgrade Functionality (OS-X/Linux)
+#——————————————————————————————————————————————————————————————————————————————————————
+bash-major-version() {
+  local bash="${1:-"/usr/bin/env bash"}"
+  ${bash} --version | head -1 | sed 's/[^0-9.]//g; s/\..*$//g'
 }
 
-# Install a modern BASH on Mac OS-X in /usr/local/bin/bash
+bash-latest-installed-version() {
+  local version=$(bash-major-version)
+  if [[ -x /usr/local/bin/bash ]]; then
+    local v=$(bash-major-version /usr/local/bin/bash)
+    [[ ${v} -gt ${version} ]] && version="${v}"
+  fi
+  printf -- "%d" "${version}"
+}
+
+bash-install-required() {
+  [[ $(bash-latest-installed-version) -lt 4 ]]
+}
+
+# Bash Installer Helpers
+bash-install() {
+  puts "Installing BASH v${bootstrap__bash_version} into ${bldylw}${bootstrap__bash_prefix}"
+  puts "Please wait..."
+  bash-compile "${bootstrap__bash_version}" "${bootstrap__bash_prefix}"
+}
+
+# Install BASH from sources
 bash-compile() {
   local version="$1"
+  local prefix="${2:-"/usr/local"}"
+  local bash_path="${prefix}/bin/bash"
+
+  if [[ -x ${bash_path} ]]; then
+    err "BASH is already installed in ${bash_path}, version $(${bash_path} --version | head 1)"
+    return 1
+  fi
+
   local bash_tar="bash-${version}.tar.gz"
-  local bash_url="http://ftp.gnu.org/gnu/bash/${bash_tar}"
+  local bash_url="http://ftp.gnu.org/gnu/b  ash/${bash_tar}"
   set -e
   local temp=/tmp/bash-sources
   rm -rf ${temp}
   mkdir -p ${temp}
+  trap "rm -rf ${temp}" EXIT
   # shellcheck disable=SC2064
   trap "cd ${PWD} || true" EXIT
-  cd ${temp}
-  curl -O "${bash_url}"
-  tar xvzf "${bash_tar}"
+  cd "${temp}" || return 1
+  is-verbose && puts "Downloading BASH from ${bash_url}..."
+  curl -sO "${bash_url}"
+  tar xzf "${bash_tar}"
   cd "bash-${version}"
-  ./configure --prefix=/usr/local
-  make -j 12
-  sudo make install
-  if [[ -x /usr/local/bin/bash ]] ; then
-    export PATH="/usr/local/bin:${PATH}"
-    grep -q /usr/local/bin/bash /private/etc/shells || {
-      echo /usr/local/bin/bash | sudo tee -a /private/etc/shells
+  is-verbose && puts "Configuring BASH in ${temp}, please wait..."
+  ./configure --prefix="${prefix}" >/dev/null
+  is-verbose && puts "Building BASH, please wait..."
+  make -j 12 --silent
+  set +e
+  make --silent install || sudo make --silent install
+  if [[ -x "${bash_path}" ]]; then
+    export PATH="${prefix}/bin:${PATH}"
+    grep -q "${bash_path}" /private/etc/shells || {
+      puts "Appending ${bash_path} to /etc/shells..."
+      echo "${bash_path}" | sudo tee -a /private/etc/shells
     }
   fi
+  puts "  ✅  BASH version ${bootstrap__bash_version} is ${bldgrn}installed in ${bootstrap__bash_prefix}."
+  return 0
 }
 
-# Brew Installer Helpers
-# Install Brew
-brew-install() {
-  command -v brew>/dev/null || {
-    puts "Installing Homebrew, please wait..."
-    /usr/bin/ruby -e \
-        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-  }
+bash-install-if-needed() {
+  is-verbose && puts "Checking if I need to install modern BASH version..."
+  bash-install-required || return
+  sudo-ask && sudo-enable
+  bash-install
 }
 
-brew-deps() {
-  set +e
-  command -v gdate >/dev/null   || brew install coreutils 1>/dev/null 2>&1 
-  command -v gnu-sed >/dev/null || brew install gnu-sed 1>/dev/null 2>&1
-}
-
-# Uninstall Brew (just for completeness, we never actually use this)
-brew-uninstall() {
-  echo y | /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
-}
-
+#——————————————————————————————————————————————————————————————————————————————————————
+# Check for locally modiifed files
 # Complain if bashmatic folder has locally modified files.
+#——————————————————————————————————————————————————————————————————————————————————————
 git-sync() {
+  is-verbose && puts "Checking if existing bashmatic folder is locally modified..."
+
   ((bootstrap__skip_git_check)) && return
 
   cd "${BASHMATIC_HOME}" >/dev/null
@@ -147,21 +196,10 @@ git-sync() {
   cd - >/dev/null
 }
 
-os-requirements() {
-  local os="$(uname -s | tr '[:upper:]' '[:lower:]')"
 
-  case ${os} in
-    darwin)  
-      darwin-requirements
-      ;;
-    linux)
-      linux-requirements
-      ;;
-    *)
-      err "Operating system ${os} is not supported."
-      exit 1
-  esac
-}
+#——————————————————————————————————————————————————————————————————————————————————————
+# LINUX
+#——————————————————————————————————————————————————————————————————————————————————————
 
 linux-requirements() {
   command -v git >/dev/null || {
@@ -171,8 +209,50 @@ linux-requirements() {
   }
 }
 
+#——————————————————————————————————————————————————————————————————————————————————————
+# OS-X
+#——————————————————————————————————————————————————————————————————————————————————————
+osx-permissions() {
+  sudo-ask && sudo-enable
+  for dir in ${CHOWN_DIRS[@]}; do
+    is-verbose && puts "Checking (and possibly changing) permissions of ${bldylw}${dir}..."
+    [[ $(stat -f %u "${dir}") -eq $(id -u) ]] && continue
+    sudo chown -R "${USER}" "${dir}"
+  done
+}
+
+# Brew Installer Helpers
+# Install Brew
+brew-install() {
+  is-verbose && puts "Installing HomeBrew if not already there..."
+  command -v brew >/dev/null || {
+    puts "Installing Homebrew, please wait..."
+    /usr/bin/ruby -e \
+      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  }
+}
+
+brew-deps() {
+  set +e
+  is-verbose && puts "Installing required brew packages..."
+  local brew_cache=/tmp/brew_cache.$$
+  trap "rm -f ${brew_cache}" EXIT
+  brew list --formulae -1 >"${brew_cache}"
+  for package in "${BREW_PACKAGES[@]}"; do
+    is-verbose && puts "Checking/installing brew package ${bldylw}${package}..."
+     grep -q "${package}" "${brew_cache}" || brew install "${package}" 1>/dev/null 2>&1
+  done
+}
+
+# Uninstall Brew (just for completeness, we never actually use this)
+brew-uninstall() {
+  echo y | /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
+}
+
 darwin-requirements-xcode() {
-  puts "Verifying and installing XCode Dependencies..."
+  is-verbose && puts "Verifying and installing XCode Dependencies..."
+  
+  command -v git >/dev/null && return
 
   local xcode_app="/Applications/Xcode.app"
   local xcode_tools="${xcode_app}/Contents/Developer"
@@ -181,32 +261,70 @@ darwin-requirements-xcode() {
   if [[ -d "${xcode_app}" && -d "${xcode_tools}" ]]; then
     [[ $(xcode-select -p) == "${xcode_tools}" ]] || sudo xcode-select --switch "${xcode_tools}"
   else
-    command -v xcodebuild >/dev/null || xcode-select --install 2>&1
+    command -v xcodebuild >/dev/null && command -v xcode-select >/dev/null && {
+      xcode-select --install 2>&1 || {
+        err "Error running xcode-select --install" "You may need to download and install XCode Command Line Tools Manually."
+        puts "We'll open the URL where you can download the tools in 5 seconds."
+        puts "You will need to login with your Apple ID."
+        sleep 1
+        puts "When you are finished installing the tools, re-run Bashmatic Install script."
+        sleep 4
+        puts "Opening Apple website..."
+        sleep 0.5
+        open "https://developer.apple.com/download/more/?=command%20line%20tools"
+        exit 1
+      }
+    }
     [[ -d "${cli_tools}" && $(xcode-select -p) == "${cli_tools}" ]] || sudo xcode-select --switch ${cli_tools} 2>/dev/null
   fi
-
-  bash -c 'command -v xcodebuild >/dev/null && sudo xcodebuild -license accept 2>&1 1>/dev/null; true ' > /dev/null
-  echo
+  is-verbose && puts "Accepting XCode license..."
+  bash -c 'command -v xcodebuild >/dev/null && sudo xcodebuild -license accept 2>&1 1>/dev/null; true ' >/dev/null
 }
 
 darwin-requirements() {
   darwin-requirements-xcode
-  [[ ! -x /usr/local/bin/bash || $BASH_VERSION =~ ^3 ]] && bash-install 
+  osx-permissions
   brew-install
   brew-deps
 }
 
-is-debug() {
- ((bootstrap__debug))
+#——————————————————————————————————————————————————————————————————————————————————————
+# Ensure OS-specific reqquirements are satisfied
+#——————————————————————————————————————————————————————————————————————————————————————
+os-requirements() {
+  local os="$(uname -s | tr '[:upper:]' '[:lower:]')"
+
+  case ${os} in
+  darwin)
+    darwin-requirements
+    ;;
+  linux)
+    linux-requirements
+    ;;
+  *)
+    err "Operating system ${os} is not supported."
+    exit 1
+    ;;
+  esac
 }
 
-#——————————————————————————————————————————————————————————
+#——————————————————————————————————————————————————————————————————————————————————————
+# Main Body
+#——————————————————————————————————————————————————————————————————————————————————————
 
 export bootstrap__debug=0
 export bootstrap__skip_git_check=0
 export bootstrap__verbose=0
 export bootstrap__bash_version="5.1-rc2"
+export bootstrap__bash_prefix="/usr/local"
 export bootstrap__sudoers_dir="/private/etc/sudoers.d"
+
+is-debug() {
+  ((bootstrap__debug))
+}
+is-verbose() {
+  ((bootstrap__verbose))
+}
 
 usage() {
   printf "
@@ -218,9 +336,10 @@ ${bldylw}DESCRIPTION:
   into /usr/local/bin/bash.
 
 ${bldylw}FLAGS:${bldpur}
-  -b, --bash-version VERSION    Install VERSION instead of ${bootstrap__bash_version}
+  -b, --bash-version VERSION    Install BASH VERSION   (default: ${bootstrap__bash_version})
+  -p, --bash-prefix PATH        Install BASH into PATH (default: ${bootstrap__bash_prefix})
   -g, --skip-git                Skip check for locally modified files
-  -v, --verbose                 See additional output
+  -v, --verbose                 See additional output (currently unused)
   -d, --debug                   Turn on 'set -x' to see all commands running
   -h, --help                    Show this help message.
   ${clr}
@@ -231,9 +350,18 @@ parse-opts() {
   # Parse additional flags
   while :; do
     case $1 in
-    -b| --bash-version)
+    -b | --bash-version)
       shift
       export bootstrap__bash_version=$1
+      shift
+      ;;
+    -p | --bash-prefix)
+      shift
+      export bootstrap__bash_prefix="$1"
+      [[ -d ${bootstrap__bash_prefix} ]] && { 
+        err "Prefix PATH ${bootstrap__bash_prefix} does not exist."
+        exit 1
+      }
       shift
       ;;
     -d | --debug)
@@ -271,15 +399,9 @@ parse-opts() {
   done
 }
 
-bootstrap-dependencies() {
-  sudo-ask
-  sudo-enable
-  os-requirements
-}
-
 bootstrap-main() {
   parse-opts "$@"
-  bootstrap-dependencies
+  os-requirements
 
   if [[ -d ${BASHMATIC_HOME} && -f ${BASHMATIC_HOME}/init.sh ]]; then
     git-sync
@@ -300,8 +422,16 @@ bootstrap-main() {
   fi
 }
 
+len="${#BASH_SOURCE[@]}"
+last_index=$((len - 1))
+[[ ${last_index} -lt 0 ]] && last_index=0
+
+set +e
 # Allow sourcing in bin/bootstrap and using it's shell functions, eg:
 # source bin/bootstrap init
-if [[ "$1" != "init" ]]; then
+if [[ -n ${ZSH_EVAL_CONEXT} && ${ZSH_EVAL_CONTEXT} =~ :file$ ]] ||
+   [[ -n ${BASH_VERSION} && "$0" != "${BASH_SOURCE[${last_index}]}" ]]; then
+  echo >/dev/null
+else
   bootstrap-main "$@"
 fi
