Dev-Setup Improvements

diff --git a/bin/dev-setup b/bin/dev-setup
--- a/bin/dev-setup
+++ b/bin/dev-setup
@@ -16,7 +16,8 @@ source "${BASHMATIC_HOME}/init.sh"
 
 output.constrain-screen-width 100
 
-export DEFAULT_RUBY_VERSION="2.7.2"
+export DEFAULT_RUBY_VERSION="$(test -f .ruby-version && cat .ruby-version || echo '3.0.0')"
+
 export DEFAULT_POSTGRESQL_VERSION="latest"
 export DEFAULT_MYSQL_VERSION="11"
 
@@ -41,7 +42,7 @@ export DevSetup__Version="0.4.0"
   elif is.numeric "${postgres_version}"; then
     package="postgresql@${postgres_version}"
   else
-    error "Invalid postgresql version: ${postgres_version}">&2
+    error "Invalid postgresql version: ${postgres_version}" >&2
     return 2
   fi
 
@@ -99,8 +100,8 @@ export DevSetup__Callbacks
   for init in ${HOME}/.bash_profile ${HOME}/.zshrc; do
     grep -q "${script}" ${init} || {
       info "Appending ${script} to ${init}..."
-      echo "[[ -s ${script} ]] && source ${script}" >> ${init}
-    } 
+      echo "[[ -s ${script} ]] && source ${script}" >>${init}
+    }
   done
 
   source "${script}"
@@ -161,7 +162,7 @@ export DevSetup__Callbacks
   )
 }
 .dev-setup.action.dev() {
-  # List of Brew Formulas to install and l`ink
+  # List of Brew Formulas to install and link
   export DevSetup__BrewPackages=("${DevSetup__BrewPackages[@]}"
     ack
     asciidoc
@@ -335,10 +336,10 @@ export DevSetup__Callbacks
 
   [[ -z ${rbenv_init} ]] && return 1
 
-  grep -q 'rbenv init' "${rcfile}" || \
+  grep -q 'rbenv init' "${rcfile}" ||
     echo "${rbenv_init}" >>"${rcfile}"
-    
-  grep -q -E 'PATH.*\.rbenv/bin' "${rcfile}" || \
+
+  grep -q -E 'PATH.*\.rbenv/bin' "${rcfile}" ||
     echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' >>"${rcfile}"
 }
 
@@ -428,7 +429,7 @@ export DevSetup__Callbacks
   brew.package.is-installed "${package}"
 
   set +e
-  brew unlink "${package}" 1>/dev/null 2>&1 
+  brew unlink "${package}" 1>/dev/null 2>&1
   run "brew link ${package} 2>/dev/null"
 
   [[ -f ~/.psqlrc ]] && mv ~/.psqlrc ~/.psqlrc.bak
@@ -463,6 +464,21 @@ _.dev-setup.action.grc() {
 
   return 0
 }
+
+# ————————————————— NO ACTIONS BELOW THIS POINT ——————————————————————————
+#
+# This file is split into two sections:
+#
+# 1) section that defines all available dev-setup actions (submodules)
+#    For a module to be defined, it must define a SHELL function named
+#    ".dev-setup.actions.<your-action-name>" where your-action-name can
+#    contain dashes, but no dots.
+#
+#    For example, ".dev-setup.action.python3" would be the action function
+#    defined above that installs python3, or it coule come from a third
+#    party python3 module.
+#
+# 2) The rest of the execution
 
 declare -a components=($(util.functions-matching.diff ".dev-setup.action."))
 declare -a components_to_install=()
@@ -684,6 +700,18 @@ dev-setup.header() {
   box.magenta-in-blue "Bashmatic Mac-OSX DevSetup Installer Version ${DevSetup__Version}"
 }
 
+dev-setup.run-action() {
+  local action_name="$1"
+  local action=".dev-setup.action.${action_name}"
+  shift
+  is.a-function "${action}" || {
+    error "Invalid Dev Setup action ${action}"
+    return 1
+  }
+  section "Evaluating Action -> ${action_name}"
+  ${action} "$@"
+}
+
 dev-setup.init() {
   brew.install
 }
@@ -805,18 +833,23 @@ dev-setup.install() {
   fi
 }
 
-if [[ $0 =~ 'dev-setup' ]]; then
+function dev-setup.run-actions() {
+  for c in "$@"; do
+    dev-setup.run-action "${c}"
+  done
+
+  dev-setup.install
+}
+
+function dev-setup.main() {
   [[ "${flag_show_header}" == "1" ]] && dev-setup.header
   dev-setup.parse-opts "$@"
   ((flag_verbose)) && run.inspect-variables-that-are starting-with flag_
   dev.setup.print-versions
-
   [[ -z ${components_to_install[*]} ]] && export components_to_install=(${components[@]})
+  dev-setup.run-action "${components_to_install[@]}"
+}
 
-  for c in "${components_to_install[@]}"; do
-    func=".dev-setup.action.${c}"
-    eval "${func}"
-  done
-
-  dev-setup.install
+if [[ $0 =~ 'dev-setup' ]]; then
+  dev-setup.main "$@"
 fi
