Fixing mysql and postgresql versioning

diff --git a/bin/dev-setup b/bin/dev-setup
--- a/bin/dev-setup
+++ b/bin/dev-setup
@@ -3,25 +3,22 @@
 source "${HOME}/.bashmatic/init.sh" 1>/dev/null
 
 run.set-all continue-on-error
+output.set-max-width 100
 
 export opt_terse=
 export ruby_version=
-export DevSetup__Version="0.1.0"
-
-.dev-setup.pg-versions() {
-  brew search postgresql@ | tr -d 'a-z@A-Z =>-' | sed '/^$/d' | sort -nr
-}
+declare -a pg_versions
+declare -a mysql_versions
+export DevSetup__Version="0.1.1"
 
 .dev-setup.detect.pg-version() {
-  declare -a pg_versions=($(brew.package.available-versions postgresql))
-  export pg_versions
+  export pg_versions=($(brew.package.available-versions postgresql))
   export latest_postgres_version=${pg_versions[0]}
   export postgres_version=${postgres_version:-${latest_postgres_version}}
 }
 
 .dev-setup.detect.mysql-version() {
-  declare -a mysql_versions=($(brew.package.available-versions mysql))
-  export mysql_versions
+  export mysql_versions=($(brew.package.available-versions mysql))
   export latest_mysql_version="${mysql_versions[0]}"
   export mysql_version=${mysql_version:-${latest_mysql_version}}
 }
@@ -146,7 +143,7 @@ export DevSetup__Callbacks
   )
 }
 
-.dev-setup.js.callbacks() {
+.dev-setup.callbacks.js() {
   if [[ -f package.json ]]; then
     if [[ -f yarn.lock ]]; then
       brew.install yarn
@@ -167,7 +164,7 @@ export DevSetup__Callbacks
     phantomjs
   )
   export DevSetup__Callbacks=(${DevSetup__Callbacks[@]}
-    .dev-setup.js.callbacks
+    .dev-setup.callbacks.js
   )
 }
 
@@ -191,13 +188,13 @@ export DevSetup__Callbacks
     ruby-completion
   )
 
-  export DevSetup__Callbacks=(${DevSetup__Callbacks[@]}
-    .dev-setup.ruby.callbacks
+  export DevSetup__Callbacks=("${DevSetup__Callbacks[@]}"
+    .dev-setup.callbacks.ruby
   )
 }
 
-.dev-setup.ruby.callbacks() {
-  ruby.install ${ruby_version}
+.dev-setup.callbacks.ruby() {
+  ruby.install "${ruby_version}"
   run "rbenv global ${ruby_version}"
   ruby.init
   ruby.bundle-install
@@ -259,19 +256,27 @@ export DevSetup__Callbacks
   )
 }
 
-.dev-setup.brew.databases() {
+.dev-setup.brew.postgres() {
   export DevSetup__BrewPackages=("${DevSetup__BrewPackages[@]}"
-    "mysql@${mysql_version}"
     "postgresql@${postgres_version}"
   )
   export DevSetup__BrewServices=("${DevSetup__BrewServices[@]}"
-    "mysql@${mysql_version}"
     "postgresql@${postgres_version}"
+  )
+}
+
+.dev-setup.brew.mysql() {
+  export DevSetup__BrewPackages=("${DevSetup__BrewPackages[@]}"
+    "mysql@${mysql_version}"
+  )
+  export DevSetup__BrewServices=("${DevSetup__BrewServices[@]}"
+    "mysql@${mysql_version}"
   )
 }
 
 declare -a components=($(util.functions-matching.diff ".dev-setup.brew."))
 declare -a components_to_install=()
+export show_header=1
 
 dev-setup.parse-opts() {
   [[ -z "$1" ]] && {
@@ -280,28 +285,32 @@ dev-setup.parse-opts() {
   }
 
   local -a default_components=(dev)
-  export default_components
+  local have_components=0
 
   # Parse additional flags
   while :; do
     case $1 in
     -g | --groups)
       shift
-      local component="$1"
-      array.includes "${component}" "${components[@]}" || {
-        error "Invalid group: $1." "Valid groups are: ${bldgrn}$(array.to.csv "${components[@]}")"
-        exit 1
-      }
-      export components_to_install=(${components_to_install[@]} "${component}")
+      local arguments="$1"
+      for component in ${arguments}; do
+        array.includes "${component}" "${components[@]}" || {
+          error "Invalid group: $1." "Valid groups are: ${bldgrn}$(array.to.csv "${components[@]}")"
+          exit 1
+        }
+        export components_to_install=(${components_to_install[@]} "${component}")
+      done
+      have_components=1
       shift
       ;;
     -d | --no-dev)
       shift
-      export default_components=()
+      default_components=()
       ;;
     -a | --all)
       shift
       export components_to_install=(${components[@]})
+      have_components=1
       ;;
     -r | --ruby-version)
       shift
@@ -311,6 +320,7 @@ dev-setup.parse-opts() {
     -p | --pg-version)
       shift
       export postgres_version="$1"
+      [[ -z "${pg_versions[*]}" ]] && .dev-setup.detect.pg-version
       array.includes "${postgres_version}" "${pg_versions[@]}" || {
         error "PostgreSQL version ${postgres_version} can not be installed via Brew." \
           "Supported versions are $(array.to.csv "${pg_versions[@]}")"
@@ -321,6 +331,7 @@ dev-setup.parse-opts() {
     -m | --mysql-version)
       shift
       export mysql_version="$1"
+      [[ -z "${mysql_versions[*]}" ]] && .dev-setup.detect.mysql-version
       array.includes "${mysql_version}" "${mysql_versions[@]}" || {
         error "MySQL version ${mysql_version} can not be installed via Brew." \
           "Supported versions are $(array.to.csv "${mysql_versions[@]}")"
@@ -330,6 +341,10 @@ dev-setup.parse-opts() {
       ;;
     -n | --dry-run)
       run::set-all dry-run-on
+      shift
+      ;;
+    -N)
+      unset show_header
       shift
       ;;
     -e | --exit-on-error)
@@ -361,14 +376,9 @@ dev-setup.parse-opts() {
     esac
   done
 
-  array.includes "ruby" "${components_to_install[@]}" && {
-    .dev-setup.detect.ruby-version
-    if [[ -z ${ruby_version} ]]; then
-      error "Can not install Ruby dependencies, without Ruby Version."
-      exit 1
-    else
-      info "Ruby dependencies will be installed for version ${ruby_version}."
-    fi
+  (("${have_components}")) || {
+    error "Please specify either -g/--groups or -a/all, or use -h/--help for Help."
+    exit 2
   }
 
   [[ ${#default_components[@]} -gt 0 ]] && {
@@ -381,6 +391,8 @@ usage() {
     cat ${BASHMATIC_HOME}/bin/.dev-setup
     return 0
   fi
+
+  dev-setup.header
 
   usage-box "dev-setup [ flags ] © Installs various packages via Homebrew." \
     "-a / --all" \
@@ -413,6 +425,42 @@ usage() {
   exit 0
 }
 
+dev.setup.print-versions() {
+  array.includes "ruby" "${components_to_install[@]}" && {
+    .dev-setup.detect.ruby-version
+    if [[ -z ${ruby_version} ]]; then
+      error "Can not install Ruby dependencies, without Ruby Version."
+      exit 1
+    else
+      h.salmon-center "Using Ruby version ${ruby_version}..."
+    fi
+  }
+
+  array.includes "postgres" "${components_to_install[@]}" && {
+    if [[ -z ${postgres_version} ]]; then
+      error "Missing PostgreSQL version!"
+      exit 1
+    else
+      h.salmon-center "Using PostgreSQL version ${postgres_version}..."
+    fi
+  }
+
+  array.includes "mysql" "${components_to_install[@]}" && {
+    if [[ -z ${mysql_version} ]]; then
+      error "Missing MySQL version!"
+      exit 1
+    else
+      h.salmon-center "Using MySQL version ${mysql_version}..."
+    fi
+  }
+}
+
+dev-setup.header() {
+  if [[ "${show_header}" == "1" ]]; then
+    box.magenta-in-blue "Bashmatic Mac-OSX DevSetup Installer" "Version ${DevSetup__Version}"
+  fi
+}
+
 dev-setup.init() {
   brew.install
 }
@@ -428,7 +476,7 @@ dev-setup.install.packages() {
 
     [[ ${code} -ne 0 ]] && {
       errors=$((errors + 1))
-      DevSetup__Errors=(${DevSetup__Errors[@]} "${command} ${package}")
+      DevSetup__Errors=("${DevSetup__Errors[@]}" "${command} ${package}")
     }
   done
   echo
@@ -470,7 +518,7 @@ dev-setup.install() {
         }
       else
         run "${command}"
-        [[ ${LibRun__LastExitCode} -eq 0 ]] || {
+        [[ "${LibRun__LastExitCode}" -eq 0 ]] || {
           failures=$((failures + 1))
         }
       fi
@@ -490,7 +538,8 @@ dev-setup.install() {
 
 if [[ $0 =~ 'dev-setup' ]]; then
   dev-setup.parse-opts "$@"
-  box.magenta-in-blue "Bashmatic Mac-OSX DevSetup Installer" "Version ${DevSetup__Version}"
+  dev-setup.header
+  dev.setup.print-versions
 
   [[ -z ${components_to_install[*]} ]] && export components_to_install=(${components[@]})
 
