Kig/dev setup improvements (#51)
* Dev-Setup Improvements

* Fix the initialization by separating declarations

* A number of fixes across the board:

 * Fixing ruby versions to include 3.0
 * Fixing is-verbose function to live in the library for dev-setup
 * Update .auto-update-disabled message
 * Reimplement array.from.command functions in BASH and ZSH; added
   tests.
 * Added new db action `list-users`

diff --git a/bin/dev-setup b/bin/dev-setup
--- a/bin/dev-setup
+++ b/bin/dev-setup
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash 
 # vim: ft=bash
 
 # shellcheck disable=2046
@@ -13,10 +13,13 @@
 }
 
 source "${BASHMATIC_HOME}/init.sh"
+source "${BASHMATIC_HOME}/lib/util.sh"
+source "${BASHMATIC_HOME}/lib/is.sh"
 
 output.constrain-screen-width 100
 
-export DEFAULT_RUBY_VERSION="2.7.2"
+export DEFAULT_RUBY_VERSION="$(test -f .ruby-version && cat .ruby-version || echo '3.0.0')"
+
 export DEFAULT_POSTGRESQL_VERSION="latest"
 export DEFAULT_MYSQL_VERSION="11"
 
@@ -41,7 +44,7 @@ export DevSetup__Version="0.4.0"
   elif is.numeric "${postgres_version}"; then
     package="postgresql@${postgres_version}"
   else
-    error "Invalid postgresql version: ${postgres_version}">&2
+    error "Invalid postgresql version: ${postgres_version}" >&2
     return 2
   fi
 
@@ -74,23 +77,6 @@ export DevSetup__Version="0.4.0"
   fi
 }
 
-declare -a DevSetup__Errors=()
-declare -a DevSetup__BrewPackages=()
-declare -a DevSetup__BrewCasks=()
-declare -a DevSetup__BrewServices=()
-declare -a DevSetup__BrewFonts=()
-# TODO: replace this array with the callback auto-detection
-#       based on the function namaing convention. For instance,
-#       for a group gpg, if a function .dev-setup.callback.gpg exists
-#       then run it.
-declare -a DevSetup__Callbacks=()
-
-export DevSetup__BrewPackages
-export DevSetup__BrewCasks
-export DevSetup__BrewServices
-export DevSetup__BrewFonts
-export DevSetup__Callbacks
-
 .dev-setup.action.z() {
   local dir=/usr/local/src/z
   local script=/usr/local/src/z/z.sh
@@ -99,8 +85,8 @@ export DevSetup__Callbacks
   for init in ${HOME}/.bash_profile ${HOME}/.zshrc; do
     grep -q "${script}" ${init} || {
       info "Appending ${script} to ${init}..."
-      echo "[[ -s ${script} ]] && source ${script}" >> ${init}
-    } 
+      echo "[[ -s ${script} ]] && source ${script}" >>${init}
+    }
   done
 
   source "${script}"
@@ -161,7 +147,7 @@ export DevSetup__Callbacks
   )
 }
 .dev-setup.action.dev() {
-  # List of Brew Formulas to install and l`ink
+  # List of Brew Formulas to install and link
   export DevSetup__BrewPackages=("${DevSetup__BrewPackages[@]}"
     ack
     asciidoc
@@ -335,10 +321,10 @@ export DevSetup__Callbacks
 
   [[ -z ${rbenv_init} ]] && return 1
 
-  grep -q 'rbenv init' "${rcfile}" || \
+  grep -q 'rbenv init' "${rcfile}" ||
     echo "${rbenv_init}" >>"${rcfile}"
-    
-  grep -q -E 'PATH.*\.rbenv/bin' "${rcfile}" || \
+
+  grep -q -E 'PATH.*\.rbenv/bin' "${rcfile}" ||
     echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' >>"${rcfile}"
 }
 
@@ -428,7 +414,7 @@ export DevSetup__Callbacks
   brew.package.is-installed "${package}"
 
   set +e
-  brew unlink "${package}" 1>/dev/null 2>&1 
+  brew unlink "${package}" 1>/dev/null 2>&1
   run "brew link ${package} 2>/dev/null"
 
   [[ -f ~/.psqlrc ]] && mv ~/.psqlrc ~/.psqlrc.bak
@@ -464,14 +450,72 @@ _.dev-setup.action.grc() {
   return 0
 }
 
-declare -a components=($(util.functions-matching.diff ".dev-setup.action."))
-declare -a components_to_install=()
-export flag_verbose=0
-export flag_force=0
-export flag_show_header=1
-export flag_run_callbacks=1
-export flag_callbacks_only=0
-export flag_on_error_abort=0
+# ————————————————— NO ACTIONS BELOW THIS POINT ——————————————————————————
+#
+# This file is split into two sections:
+#
+# 1) section that defines all available dev-setup actions (submodules)
+#    For a module to be defined, it must define a SHELL function named
+#    ".dev-setup.actions.<your-action-name>" where your-action-name can
+#    contain dashes, but no dots.
+#
+#    For example, ".dev-setup.action.python3" would be the action function
+#    defined above that installs python3, or it coule come from a third
+#    party python3 module.
+#
+# 2) The rest of the execution
+
+declare -a components
+declare -a components_to_install
+declare -a DevSetup__Errors
+declare -a DevSetup__BrewPackages
+declare -a DevSetup__BrewCasks
+declare -a DevSetup__BrewServices
+declare -a DevSetup__BrewFonts
+
+function dev-setup.initialize() {
+  export DevSetup__Initialized=${DevSetup__Initialized:-0}
+
+  ((DevSetup__Initialized)) && return 0
+
+  export DevSetup__Initialized=1
+
+  # TODO: replace this array with the callback auto-detection
+  #       on the function namaing convention. For instance,
+  #       for a group gpg, if a function .dev-setup.callback.gpg exists
+  #       then run it.
+  declare -a DevSetup__Callbacks
+
+  export DevSetup__BrewPackages=()
+  export DevSetup__BrewCasks=()
+  export DevSetup__BrewServices=()
+  export DevSetup__BrewFonts=()
+  export DevSetup__Callbacks=()
+
+  export components=($(util.functions-matching.diff ".dev-setup.action."))
+  export components_to_install=()
+
+  export flag_verbose=0
+  export flag_force=0
+  export flag_show_header=1
+  export flag_run_callbacks=1
+  export flag_callbacks_only=0
+  export flag_on_error_abort=0
+
+  return 0
+}
+
+dev-setup.print-components() {
+  local -a list="$@"
+  if [[ ${#list[@]} -eq 0 ]]; then
+    warning "Warning: empty component list."
+    return 1
+  else
+    info "Detected the following components:"
+    array.to.bullet-list "$@" | sedx 's/•/      • /g'
+  fi
+  return 0
+}
 
 dev-setup.parse-opts() {
   [[ -z "$1" ]] && {
@@ -485,6 +529,10 @@ dev-setup.parse-opts() {
   # Parse additional flags
   while :; do
     case $1 in
+    -l | --list)
+      shift
+      dev-setup.print-components "${components[@]}"
+     ;;
     -g | --groups)
       shift
       local arguments="$1"
@@ -684,8 +732,20 @@ dev-setup.header() {
   box.magenta-in-blue "Bashmatic Mac-OSX DevSetup Installer Version ${DevSetup__Version}"
 }
 
-dev-setup.init() {
-  brew.install
+dev-setup.run-action() {
+  local action_name="$1"
+  shift
+  local action=".dev-setup.action.${action_name}"
+  set +e
+
+  is.a-function ${action} || {
+    error "Invalid Dev Setup action ${action_name}" "function ${action} is not defined."
+    return 1
+  }
+  section "Loading packages from -> ${action_name}"
+  cursor.up 2
+
+  eval "${action} $*"
 }
 
 dev-setup.install.packages() {
@@ -800,23 +860,41 @@ dev-setup.install() {
     warning \
       "Setup completed, but with some failures." \
       "Total of ${failures} failures out of ${total} commands were detected and skipped."
-    echo
-    h.e "ATTENTION: the following commands failed:" "${DevSetup__Errors[@]}"
+        echo
+        h.e "ATTENTION: the following commands failed:" "${DevSetup__Errors[@]}"
   fi
 }
 
-if [[ $0 =~ 'dev-setup' ]]; then
+function dev-setup.invoke-actions() {
+  for c in $@; do
+    dev-setup.run-action "${c}"
+  done
+  cursor.down 3
+}
+
+function dev-setup.run-actions() {
+  if [[ ${AppCurrentOS} =~ darwin ]]; then
+    brew.install
+  fi
+
+  dev-setup.invoke-actions "$@"
+  dev-setup.install
+}
+
+function dev-setup.main() {
+  # dev-setup.initialize
   [[ "${flag_show_header}" == "1" ]] && dev-setup.header
+
   dev-setup.parse-opts "$@"
   ((flag_verbose)) && run.inspect-variables-that-are starting-with flag_
   dev.setup.print-versions
 
   [[ -z ${components_to_install[*]} ]] && export components_to_install=(${components[@]})
+  dev-setup.print-components "${components_to_install[@]}"
+  dev-setup.run-actions "${components_to_install[@]}"
+}
 
-  for c in "${components_to_install[@]}"; do
-    func=".dev-setup.action.${c}"
-    eval "${func}"
-  done
-
-  dev-setup.install
+if [[ $0 =~ 'dev-setup' ]]; then
+  util.eval-function-body "dev-setup.initialize"
+  dev-setup.main "$@"
 fi
