Adding password generation routines to bashmatic.
 * Also, updated `bin/specs` script to be capable of running
   individual specs by partial name, eg `bin/specs util`.

diff --git a/bin/specs b/bin/specs
--- a/bin/specs
+++ b/bin/specs
@@ -6,37 +6,89 @@ source "lib/Loader.bash"
 
 export ProjectRoot=$(pwd)
 export BatsRoot=${ProjectRoot}/.bats
-export BatsTestCase=
-export SingleTestFile="test/all.bats"
+declare -a TestFiles=()
 
 export True=1
 export False=0
 
-usage() {
+specs::test-filename() {
+  file=$1
+  for f in ${file} "test/${file}" "test/${file}_tests.bats"; do
+    if [[ -s ${f} ]]; then
+      printf "%s" ${f}
+      break
+    fi
+  done
+}
+
+specs::usage() {
   echo
-  printf "USAGE\n    ${bldgrn}bin/specs [ options ]${clr}\n\n"
+  printf "USAGE\n    ${bldgrn}bin/specs [ test1 test2 ... ]${clr}\n\n"
+  printf "    ${txtblu}where test1 can be a full filename, or a partial, eg.\n"
+  printf "    ${txtblu}'test/util_tests.bats' or just 'util'.\n\n"
+
   printf "DESCRIPTION\n    ${txtblu}Run BASH tests using Bats framework\n"
   printf "    ${txtblu}Use to run the Bats Test Suite.\n\n"
   printf "OPTIONS\n"
-  printf "    -j | --join     Join all tests into a single file\n"
   printf "    -h | --help     Show help message\n\n"
+
+  exit 0
+}
+
+specs::prepare() {
+  [[ ${PATH} =~ ${ProjectRoot} ]] || export PATH="${ProjectRoot}/bin:${PATH}"
+  [[ ! -d ${BatsRoot} ]] && run "git clone https://github.com/kigster/bats.git ${BatsRoot}"
+  [[ -d ${BatsRoot} ]] && run "cd ${BatsRoot} && git pull --rebase 2>/dev/null; cd -"
+  [[ -L bin/bats ]] && run "cd ${BatsRoot} && ./install.sh ${ProjectRoot}; cd ${ProjectRoot}"
+}
+
+specs::run-file() {
+  local file="$1"
+  if [[ -z "${file}" ]]; then
+    error "No argument provided"
+    return 1
+  fi
+  if [[ ! -s "${file}" ]]; then
+    error "File ${file} is not found."
+    return 1
+  fi
+  hl::green "${file}"
+  set -e
+  bats -p "${file}"
+  set +e
+}
+
+specs::select-files() {
+  export os=$(uname -s | tr [A-Z] [a-z])
+  if [[ -z ${TestFiles[*]} ]]; then
+    TestFiles=($(ls -1 test/*_test.*))
+    [[ -d "test/${os}" ]] && TestFiles=(${TestFiles[@]} $(ls -1 test/${os}/*_test.*))
+  fi
+  export TestFiles
+}
+
+specs::run-all() {
+  for file in ${TestFiles[@]}; do
+    specs::run-file "${file}"
+  done
+}
+
+specs::main() {
+  specs::prepare
+  specs::select-files
+
+  specs::run-all
 }
 
 trap 'printf "\n\n\n${bldred}BOOOOM! Ctrl-C will set you free...${clr}\n\n"; exit 1' SIGINT
-
-ConfigJoinFiles=${False}
 
 # Parse additional flags
 while :; do
   case $1 in
     -h|-\?|--help)
       shift
-      usage
+      specs::usage
       exit 0
-      ;;
-    -j|--join)
-      shift
-      ConfigJoinFiles=${True}
       ;;
     --) # End of all options; anything after will be passed to the action function
       shift
@@ -48,62 +100,10 @@ while :; do
       shift
       ;;
     *)  # Default case: If no more options then break out of the loop.
-      file="$1"
-      [[ -f ${file} && -z ${BatsTestCase} ]] && BatsTestCase="${file}"; shift
-      break
+      [[ -z ${1} ]] && break
+      file=$(specs::test-filename $1)
+      [[ -n "${file}" ]] && TestFiles=(${TestFiles[@]} ${file}); shift
   esac
 done
 
-test::setup-joined-file() {
-  run "rm -f ${SingleTestFile} && touch ${SingleTestFile}"
-  printf "#!/usr/bin/env bats\nload test_helper\n\n" > ${SingleTestFile}
-}
-
-run-spec() {
-  local file=${1}
-  if [[ ${ConfigJoinFiles} -eq ${True} ]] ; then
-    cat ${file} | sed '/test_helper/d;/source/d' >> ${SingleTestFile}
-  else 
-    h1 "Running test file ${bldylw}${file}"
-    bats -p "${file}"
-  fi
-}
-
-if [[ ${ConfigJoinFiles} -eq ${False} ]] ; then
-  h2 "Running Tests one file at a time."
-  trap '' EXIT
-else
-  h2 "Running Tests by Concatenating all files"
-  test::setup-joined-file
-  trap "rm -f ${SingleTestFile}" EXIT
-fi
-
-[[ ${PATH} =~ ${ProjectRoot} ]] || export PATH="${ProjectRoot}/bin:${PATH}"
-
-[[ ! -d ${BatsRoot} ]] && run "git clone https://github.com/kigster/bats.git ${BatsRoot}"
-[[ -f bin/bats ]] || run "cd ${BatsRoot} && ./install.sh ${ProjectRoot}; cd ${ProjectRoot}"
-
-set -e
-
-if [[ -f "${BatsTestCase}" ]] ; then
-  run-spec ${BatsTestCase}
-  exit $?
-else
-  for file in $(ls -1 test/*_test.*); do
-    run-spec ${file} 
-  done
-fi
-
-export os=$(uname -s | tr [A-Z] [a-z])
-
-if [[ -d "test/${os}" && -n $(ls -1 test/${os}) ]]; then
-  for file in $(ls -1 test/${os}/*_test.*); do
-    run-spec ${file}
-  done
-fi
-
-if [[ ${ConfigJoinFiles} -eq ${True} ]]; then 
-  bats -p "${SingleTestFile}"
-fi
-
-
+specs::main "$@"
